on: push
name: 🚀 Deploy to nobir on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.nobir-hasan.com
        username: easyupseba@websites.nobir-hasan.com
        password: ${{ secrets.MY_PASS }}
